name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build unsigned APK
        run: |
          ./gradlew assembleRelease \
            -x signRelease \
            -x bundleRelease

      - name: Rename APK
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/release/app-release-unsigned.apk artifacts/app-unsigned-${{ github.sha }}.apk

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: app-unsigned
          path: artifacts/app-unsigned-${{ github.sha }}.apk
